import { createSlice } from "@reduxjs/toolkit";
import { fetchProducts } from "../api/ProductApi";
import Product from "../../model/Product";

type ProductState = {
    status: "loading" | "idle",
    error: string | null,
    list: Product[]
}

const initialState: ProductState = {
    status: "idle",
    error: null,
    list: []
}
const ProductSlice = createSlice({
    name: "products",
    initialState,
    // contains actions which are dispatched from view
    reducers: {},
    // extraReducers are for actions generated by Thunk
    extraReducers: (builder) => {
        builder.addCase(fetchProducts.pending, (state, { payload }) => {
            state.status = "loading";
            state.list = [];
            state.error = null;
        })
        builder.addCase(fetchProducts.fulfilled, (state, action) => {
            state.status = "idle";
            state.list.push(...action.payload)
            state.error = null;
        })
        builder.addCase(fetchProducts.rejected, (state, action) => {
            state.status = "idle";
            state.error = action.error.message!
            state.list = [];
        })
    }
});

export const productReducer = ProductSlice.reducer;